### ISSUE TITLE
Путь к файлу с именами в NameExtractor захардкожен внутри класса

### ISSUE THREAD

**Issue by Sirius504** [shoproishodet/CONSOLE_MMORPG#2]
При попытке первой сборки проекта выводится ошибка:

> `Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\C#\MMORPG\npc_names.txt'.
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
>    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
>    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
>    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
>    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
>    at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
>    at System.IO.File.ReadAllLines(String path)
>    at NameExtractor..ctor() in D:\Projects\sanek_rpg\NameExtractor.cs:line 3
>    at Program.Main(String[] args) in D:\Projects\sanek_rpg\Program.cs:line 9`

**Comment by Sirius504** [comment]
@shoproishodet  Если мы это пофиксили, то закрой issue пожалуйста.
